services:
  autodroid_postgres:
    container_name: autodroid_postgres
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=autodroid
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.runtime/database/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - autodroid_network

  autodroid_redis:
    container_name: autodroid_redis
    image: redis:alpine
    volumes:
      - ./.runtime/database/redis:/data
    restart: always
    networks:
      - autodroid_network

  autodroid_mongo:
    container_name: autodroid_mongo
    image: mongo:6
    volumes:
      - ./.runtime/database/mongo:/data/db
    restart: always
    networks:
      - autodroid_network

  autodroid_api:
    container_name: autodroid_api
    image: malwaredatalab/autodroid-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # General
      - APP_URL=http://localhost:3333
      - APP_PORT=3333
      - NODE_ENV=development
      - DEFAULT_LANGUAGE=en
      - TZ=UTC
      - DEBUG=false

      # Cors
      - CORS_ALLOWED_FROM=http://localhost:3000,*

      # Database
      - DATABASE_URL=postgresql://postgres:docker@autodroid_postgres:5432/autodroid?schema=public
      - DATABASE_LOGGER_ENABLED=false

      # Non-relational database
      - NON_RELATIONAL_DATABASE_URL=mongodb://autodroid_mongo:27017/autodroid
      - NON_RELATIONAL_DATABASE_LOGGER_ENABLED=false

      # Redis
      - REDIS_HOST=autodroid_redis
      - REDIS_PORT=6379
      - REDIS_USER=
      - REDIS_PASS=
      - REDIS_DB=1

      # Providers
      - FIREBASE_AUTHENTICATION_PROVIDER_PROJECT_ID=
      - FIREBASE_AUTHENTICATION_PROVIDER_CLIENT_EMAIL=
      - FIREBASE_AUTHENTICATION_PROVIDER_PRIVATE_KEY=

      - GOOGLE_STORAGE_PROVIDER_PROJECT_ID=
      - GOOGLE_STORAGE_PROVIDER_CLIENT_EMAIL=
      - GOOGLE_STORAGE_PROVIDER_PRIVATE_KEY=
      - GOOGLE_STORAGE_PROVIDER_BUCKET_NAME=

      - NODEMAILER_EMAIL_NOTIFICATION_PROVIDER_GMAIL_USER=
      - NODEMAILER_EMAIL_NOTIFICATION_PROVIDER_GMAIL_APP_PASSWORD=

      # Feature
      - SENTRY_DSN=

      - EMAIL_NOTIFICATION_PROVIDER_EMAIL_OVERRIDE_TO_EMAILS=
      - EMAIL_NOTIFICATION_PROVIDER_EMAIL_DEFAULT_BCC_EMAILS=

      - ADMIN_EMAILS=

      - JOBS_ENABLED=true

      - FRONTEND_URL=https://localhost:3000

      - STORAGE_PROVIDER_PUBLIC_READ_URL_EXPIRATION=1h
      - STORAGE_PROVIDER_PUBLIC_WRITE_URL_EXPIRATION=5m

      - WORKER_REFRESH_TOKEN_SECRET=your-refresh-secret-key
      - WORKER_REFRESH_TOKEN_EXPIRATION=30d
      - WORKER_ACCESS_TOKEN_SECRET=your-access-secret-key
      - WORKER_ACCESS_TOKEN_EXPIRATION=1h
      - WORKER_MAX_CONCURRENT_JOBS=3

      - PROCESSING_DEFAULT_KEEP_UNTIL=30d
      - PROCESSING_ALLOWED_KEEP_UNTIL_EXTEND=30d
    ports:
      - 3333:3333
    command: ./wait-for.sh autodroid_postgres:5432 -q -- ./wait-for.sh autodroid_mongo:27017 -q -- ./wait-for.sh autodroid_redis:6379 -q -- sh -c "yarn run-s prisma:generate prisma:prod start:prod"
    depends_on:
      - autodroid_postgres
      - autodroid_mongo
      - autodroid_redis
    healthcheck:
      test: wget --spider -q http://autodroid_api:3333/health/readiness || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: always
    networks:
      - autodroid_network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 30 autodroid_api

networks:
  autodroid_network:
    name: autodroid_network
